#!/bin/bash

# File preview handler for lf.
# Luke Smith's lf scope with kitty image protocol support(thanks Eric Murphy)
# NOTE: image preview takes a few seconds to display

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

file=$1
w=$2
h=$3
x=$4
y=$5

image() {
  if [ -f "$1" ] && [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] ; then
    kitty +kitten icat --silent --stdin no --transfer-mode file --place "${w}x${h}@${x}x${y}" "$1" < /dev/null > /dev/tty
  else
    mediainfo "$6"
  fi
}

ifub() {
  [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ]
}

# Note that the cache file name is a function of file information, meaning if
# an image appears in multiple places across the machine, it will not have to
# be regenerated once seen.

case "$(file --dereference --brief --mime-type -- "$1")" in
  image/avif) CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && convert "$1" "$CACHE.jpg"
    image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1" ;;
  image/vnd.djvu)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && djvused "$1" -e 'select 1; save-page-with /dev/stdout' | convert -density 200 - "$CACHE.jpg" > /dev/null 2>&1
    image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1" ;;
  image/*) image "$1" "$2" "$3" "$4" "$5" "$1" ;;
  text/html) lynx -width="$4" -display_charset=utf-8 -dump "$1" ;;
  text/troff) man ./ "$1" | col -b ;;
  text/* | */xml | application/json | application/x-ndjson) bat --terminal-width "$(($4-2))" -f "$1" ;;
  audio/* | application/octet-stream) mediainfo "$1" || exit 1 ;;
  video/* )
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE" ] && ffmpegthumbnailer -i "$1" -o "$CACHE" -s 0
    image "$CACHE" "$2" "$3" "$4" "$5" "$1"
    ;;
  */pdf)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE.jpg" ] && pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
    image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
    ;;
  */epub+zip|*/mobi*)
    CACHE="${XDG_CACHE_HOME:-$HOME/.cache}/lf/thumb.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | cut -d' ' -f1)"
    [ ! -f "$CACHE.jpg" ] && gnome-epub-thumbnailer "$1" "$CACHE.jpg"
    image "$CACHE.jpg" "$2" "$3" "$4" "$5" "$1"
    ;;
  application/*zip) atool --list -- "$1" ;;
  *opendocument*) odt2txt "$1" ;;
  application/pgp-encrypted) gpg -d -- "$1" ;;
esac
exit 1
