#!/bin/bash

# install packages
packages=(
  alsa-lib
  alsa-plugins
  faudio
  gamemode
  giflib
  gnutls
  gst-plugins-base-libs
  gtk3
  innoextract
  irqbalance
  lib32-alsa-lib
  lib32-alsa-plugins
  lib32-faudio
  lib32-gamemode
  lib32-giflib
  lib32-gnutls
  lib32-gst-plugins-base-libs
  lib32-gtk3
  lib32-libgcrypt
  lib32-libgpg-error
  lib32-libjpeg-turbo
  lib32-libldap
  lib32-libpng
  lib32-libpng12
  lib32-libpulse
  lib32-libva
  lib32-libxcomposite
  lib32-libxinerama
  lib32-libxslt
  lib32-mangohud
  lib32-mpg123
  lib32-ncurses
  lib32-ocl-icd
  lib32-openal
  lib32-sqlite
  lib32-v4l-utils
  lib32-vkd3d
  libgcrypt
  libgpg-error
  libjpeg-turbo
  libldap
  libpng
  libpulse
  libva
  libxcomposite
  libxinerama
  libxslt
  lutris
  mangohud
  mpg123
  ncurses
  ocl-icd
  openal
  sqlite
  steam
  v4l-utils
  vkd3d
  wine-mono
  wine-staging
)


yay --sync --noconfirm --needed "${packages[@]}"

