#!/bin/bash
notify-send "Autorandr: monitor change detected"

wallpaper=~/.dotfiles/street.jpg

feh --bg-fill "$wallpaper"
betterlockscreen --update "$wallpaper"

# fix bspwm fullscreen issues using laptop + external display 
bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor eDP-1 --remove
