#!/bin/bash
notify-send "Autorandr: monitor change detected"

wallpaper=~/.dotfiles/street.jpg

feh --bg-fill "$wallpaper"
betterlockscreen --update "$wallpaper"

# fix bspwm fullscreen issues using laptop + external display 
display_1=eDP-1
display_2=HDMI-1
if [[ $(xrandr -q | grep "$display_2 connected") ]]; then
  bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
  bspc monitor "$display_1" --remove
else
  bspc monitor "$display_1" -d 1 2 3 4 5 6 7 8 9 10
  bspc monitor "$display_2" --remove
fi
