#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# monitor magic
sleep 1; autorandr --change &

# hack to handle laptop + external monitor
if [[ $( xrandr -q | grep "HDMI-1 connected" ) ]]; then
  bspc monitor HDMI-1 -d 1 2 3 4 5 6 7 8 9 10
  bspc monitor eDP-1 --remove
else
  bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

# bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          10

bspc config focused_border_color "#BF4E6D"
bspc config normal_border_color "#000000"
bspc config active_border_color "#7571f9"
bspc config presel_feedback_color "#777777"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2'
bspc rule -a Google-chrome desktop='^2'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a obsidian desktop='^4'
bspc rule -a steam desktop='^5' state=floating
bspc rule -a Lutris desktop='^5' state=floating
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^10'
bspc rule -a KeePassXC state=floating
bspc rule -a zoom state=floating center=on follow=on border=off
bspc rule -a Guvcview state=floating
bspc rule -a '*:*:Picture in picture' state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a hl2_linux desktop='^6' state=fullscreen
bspc rule -a Element desktop='^3'

xss-lock --transfer-sleep-lock -- "betterlockscreen --lock" --nofork &
xautolock -time 10 -locker "idle-lock" &

nm-applet --no-agent &
pgrep -x cbatticon > /dev/null || cbatticon &

feh --bg-fill ~/.dotfiles/sakura.jpg
picom --daemon

playerctld daemon

# polybar
~/.config/polybar/launch.sh

ibus-daemon --replace --xim --daemonize

festival --server &

keepassxc &
discord --start-minimized
