#!/bin/sh


if [ ! "$(command -v bundler)" ] || [ ! "$(command -v jq)" ]; then
  if [ ! "$(command -v bundler)" ] && [ ! "$(command -v jq)" ]; then
    echo "error: bundler and jq not found"
  elif  [ ! "$(command -v bundler)" ]; then
    echo "error: bundler not found"
  elif [ ! "$(command -v jq)" ]; then
    echo "error: jq not found"
  fi
  exit
fi


tmp_dir=$(mktemp -d)
emoji_file="$HOME/.local/share/emojis.json"

git clone --filter=blob:none https://github.com/Mange/emoji-data "$tmp_dir"

cd "$tmp_dir" || exit

# determine whether to use doas or sudo
if [ "$(command -v doas)" ]; then
  make setup || doas bundle install

elif [ "$(command -v sudo)" ]; then
  make setup || sudo bundle install
else
  echo "Neither doas or sudo were found. Please install either of them to proceed."
fi


make all

# exit if build was not successfull
cd data || exit

cp all_emojis.json "$emoji_file"
