#!/bin/sh

if [ ! "$(command -v bundler)" ] || [ ! "$(command -v jq)" ]; then
  echo "ruby or jq is not installed, aborting" >&2 
  exit
fi


tmp_dir=$(mktemp -d)
emoji_file="$HOME/.local/share/emojis.json"

git clone --filter=blob:none https://github.com/Mange/emoji-data "$tmp_dir"

cd "$tmp_dir" || exit
make setup || sudo bundle install
make all

# exit if build was not successfull
cd data || exit

cp all_emojis.json "$emoji_file"
