#!/bin/sh

# ensure profiles directory is created
if [ ! -d "$HOME/.mozilla/" ]; then
    sleep 5 && killall firefox &
    firefox -headless &
    wait
fi

default_profile=$(grep "Default=.*\.default*" "$HOME/.mozilla/firefox/profiles.ini" | cut -d"=" -f2)
profile_path=$(find ~/.mozilla/firefox/ -type d -name $default_profile)
temp_file=$(mktemp)

# fetch betterfox user.js
curl https://raw.githubusercontent.com/yokoffing/Betterfox/main/user.js --output "$temp_file"

# append smooth scroll settings and betterfox overrides to user.js
echo '


// overrides
user_pref("identity.fxaccounts.enabled", true);
user_pref("browser.tabs.tabmanager.enabled", true);
user_pref("privacy.userContext.ui.enabled", false);
user_pref("browser.search.suggest.enabled", true);
user_pref("browser.urlbar.suggest.quicksuggest.nonsponsored", true);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("findbar.highlightAll", true);
user_pref("browser.safebrowsing.downloads.remote.enabled", true);
user_pref("browser.contentblocking.category", "standard");
user_pref("permissions.default.desktop-notification", 0);
user_pref("permissions.default.geo", 0);
user_pref("devtools.toolbox.host", "right");
user_pref("privacy.history.custom", false);
user_pref("ui.key.menuAccessKeyFocuses", false);
user_pref("ui.prefersReducedMotion", 1);
user_pref("accessibility.typeaheadfind.enablesound", false);
user_pref("general.smoothScroll", false);
' >> "$temp_file"

# move user.js to default firefox profile
cp "$temp_file" "$profile_path"/user.js
