#!/bin/bash

herbe_src="$HOME/Downloads/git/herbe"
xresources_patch="/tmp/11.diff"

curl https://patch-diff.githubusercontent.com/raw/dudik/herbe/pull/11.diff --output "$xresources_patch"
git clone https://github.com/dudik/herbe "$herbe_src"

cd "$herbe_src" || exit

git apply "$xresources_patch"

sudo make install

xrdb ~/.Xresources
