#!/bin/sh

# NOTE: make sure perl-lwp-protocol-https is installed or scripts won't load

# create directories
mkdir --parent ~/.local/share/irssi/scripts/autorun/ /tmp/irssi-scripts/
scripts_dir=~/.local/share/irssi/scripts/
tmp_dir=/tmp/irssi-scripts
url="https://raw.githubusercontent.com/irssi/scripts.irssi.org/master/scripts/"
scripts=(nickcolor)
for script in "${scripts[@]}"; do
  curl "$url$script.pl" -o "$tmp_dir/$script.pl"
  mv "$tmp_dir/$script.pl" "$scripts_dir"
  ln -sf "$scripts_dir/$script.pl" "$scripts_dir/autorun"
done
