#!/bin/sh
echo '
Section "ServerFlags"
    Option "DontZap" "false"
EndSection

Section "InputClass"
    Identifier      "Keyboard Defaults"
    MatchIsKeyboard "yes"
    Option          "XkbOptions" "terminate:ctrl_alt_bksp"
EndSection' | tee /etc/X11/xinit/xinitrc.d/40-kill-x.conf

