#!/bin/bash
sudo pacman --sync --refresh --sysupgrade --noconfirm
sudo pacman --sync git --noconfirm --needed

# yay
mkdir --parents ~/Downloads/git
cd ~/Downloads/git
git clone https://aur.archlinux.org/yay-bin.git
cd yay-bin
yes | makepkg --syncdeps --install

cd ~/.dotfiles

# enable multilib
sudo sed --in-place "/\[multilib\]/,/Include/"'s/^#//' /etc/pacman.conf
# enable parallel downloads
sudo sed --in-place 's/#ParallelDownloads = 5/ParallelDownloads = 20/g' /etc/pacman.conf
# enable colorful pacman output
sudo sed --in-place '/# Color/s/^#//g' /etc/pacman.conf

# allocate more cpu cores to make
sudo sed -in-place --regexp-extended "s/#MAKEFLAGS=\"-j[1-9]\"/MAKEFLAGS=\"-j$(nproc)\"/g" /etc/makepkg.conf

sudo pacman --sync --refresh --sysupgrade --noconfirm

# install packages
yay --sync --noconfirm --needed - < packages

