#!/bin/bash

systemctl --user enable mpd.socket
systemctl --user disable pulseaudio.socket pulseaudio.service
systemctl --user --now enable mpd-mpris
systemctl enable avahi-daemon
systemctl mask systemd-rfkill.service
systemctl mask systemd-rfkill.socket
systemctl enable bluetooth.service
systemctl enable --now irqbalance.service
systemctl enable cups.socket
systemctl enable libvirtd
systemctl enable --user syncthing.service
systemctl enable cpupower.service
systemctl enable ufw.service
systemctl disable iptables.service
