#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &


# monitor magic
(sleep 3 && autorandr --change) &

# Set decoration geometry
berryc border_width       5
berryc inner_border_width 3
berryc title_height       30
berryc top_gap            30

# Set decoration colors
berryc focus_color         292D3E
berryc unfocus_color       292D3E
berryc inner_focus_color   FFCB6B
berryc inner_unfocus_color 565679
berryc text_focus_color    ffffff
berryc text_unfocus_color  eeeeee

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"


xss-lock --transfer-sleep-lock -- "betterlockscreen --lock" --nofork &
xautolock -time 10 -locker "idle-lock" &

nm-applet --no-agent &
cbatticon &

feh --bg-fill ~/.dotfiles/street.jpg

picom --daemon

playerctld daemon

# conky &

tint2 &
# terminate instances of polybar that are already running
# killall -q polybar
# polybar &
# flameshot &

ibus-daemon -rxR &

discord --start-minimized --tray
