#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &


# monitor magic
(sleep 3 && autorandr --change) &

# Set decoration geometry
berryc border_width       1
berryc inner_border_width 0
berryc title_height       0
berryc top_gap            0

# Set decoration colors
berryc focus_color         ee6ff8
berryc unfocus_color       171717
berryc inner_focus_color   171717
berryc inner_unfocus_color 171717
berryc text_focus_color    dddddd
berryc text_unfocus_color  777777

# Other options
berryc smart_place "true"
berryc draw_text   "true"
berryc edge_lock   "true"
berryc set_font    "Dina-9"


xss-lock --transfer-sleep-lock -- "betterlockscreen --lock" --nofork &
xautolock -time 10 -locker "idle-lock" &

nm-applet --no-agent &
cbatticon &

feh --bg-fill ~/.dotfiles/street.jpg

picom --daemon

playerctld daemon

# conky &

# terminate instances of polybar that are already running
killall -q polybar
polybar &

ibus-daemon -rxR &

discord --start-minimized --tray
