#!/bin/sh

userresources=${XDG_CONFIG_HOME:-~/.config}/X11/Xresources
usermodmap=${XDG_CONFIG_HOME:-~/.config}/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

[ -f "$sysresources" ] && xrdb -merge $sysresources

[ -f "$sysmodmap" ] && xmodmap $sysmodmap

[ -f "$userresources" ] && xrdb -merge "$userresources"

[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

eval "$(dbus-launch --sh-syntax --exit-with-session)"

gentoo-pipewire-launcher &

if [ "$(xrandr -q | grep -c "HDMI1 connected")" -eq 1 ]; then
  xrandr --output HDMI1 --mode 1920x1080 -r 71
  xrandr --output eDP1 --off
else
  xrandr --output eDP1 --auto
fi

sowm
