#!/bin/sh

userresources=$HOME/.config/X11/Xresources
usermodmap=$HOME/.config/X11/Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then

  xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
  xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then

  xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
  xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

xset b off
xset +dpms
xset s 300 5
xss-lock -l -- slock &

eval "$(dbus-launch --sh-syntax --exit-with-session)"

gentoo-pipewire-launcher &

mpd

playerctld daemon

xcompmgr &

unclutter -b

while true; do
  xsetroot -name "$(date +"%m/%d %I:%M %p")"
  sleep 1
done &

if [ $(xrandr -q | grep -c "HDMI1 connected") -eq 1 ]; then
  xrandr --output HDMI1 --mode 1920x1080 -r 71
  xrandr --output eDP1 --off
else
  xrandr --output eDP1 --auto
fi

hsetroot -full "$WALLPAPER"

while true; do
  # Log stderror to a file
  dwm 2>/tmp/dwm.log
done
